#!/usr/bin/env python3
"""aggregate_docs — compile every repo's ai-docs/ into norikit/ecosystem/ (a read-only mirror).

One-stop ecosystem knowledge base: the **doctrine** (this repo's `ai-docs/`) plus each tool's
`ai-docs/`, so the whole ecosystem's design is readable without cloning 13 repos. The source of
truth stays in each repo (coupled to its code); this is a generated, regenerated snapshot —
every mirrored file carries a DO NOT EDIT header.

Reads each sibling repo's `ai-docs/` from **origin/main** (`git show`) and writes
`norikit/ecosystem/projects/<repo>/…` + a generated index.

Usage:  python3 tools/aggregate_docs.py [--check]
Python 3.11+, stdlib only. Dev-time tooling — not a runtime dependency.
(The scheduled org-doctor Action should `git fetch` repos first so origin/main is current.)
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parent
ORG_ROOT = REPO.parent
ECOSYSTEM = REPO / "ecosystem"
SELF = {"template", "norikit", ".github"}          # infra: source/hub/profile, not mirrored
GEN = "<!-- DO NOT EDIT — generated mirror of {src} by tools/aggregate_docs.py. Edit the source. -->\n\n"


def git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True).stdout


def aidocs_on_main(repo: Path) -> list[str]:
    out = git(repo, "ls-tree", "-r", "--name-only", "origin/main", "ai-docs/")
    return sorted(l for l in out.splitlines() if l.endswith(".md"))


def discover() -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}
    for p in sorted(ORG_ROOT.iterdir()):
        if (p / ".git").exists() and p.name not in SELF:
            files = aidocs_on_main(p)
            if files:
                found[p.name] = files
    return found


def build() -> dict[Path, str]:
    found = discover()
    out: dict[Path, str] = {}
    for repo, files in found.items():
        for rel in files:                          # e.g. ai-docs/decisions.md
            content = git(ORG_ROOT / repo, "show", f"origin/main:{rel}")
            out[ECOSYSTEM / "projects" / repo / Path(rel).name] = GEN.format(src=f"{repo}/{rel}") + content

    idx = ["<!-- DO NOT EDIT — generated by tools/aggregate_docs.py. -->", "",
           "# norikit ecosystem — compiled knowledge base", "",
           "Read-everything mirror. **Doctrine** (mission · conventions · framework · roster) lives in",
           "[`../ai-docs/`](../ai-docs/). **Per-project** design docs are mirrored below from each repo's",
           "`ai-docs/` — the source of truth stays in the repo, coupled to its code.", "",
           "## Projects", ""]
    for repo in sorted(found):
        links = " · ".join(f"[{Path(f).stem}](projects/{repo}/{Path(f).name})" for f in found[repo])
        idx.append(f"- **{repo}** — {links}")
    missing = [p.name for p in sorted(ORG_ROOT.iterdir())
               if (p / ".git").exists() and p.name not in SELF and p.name not in found]
    if missing:
        idx += ["", "## Not yet mirrored", "",
                "_No `ai-docs/` on `main` yet (bare or pending migration):_ " + ", ".join(missing) + "."]
    out[ECOSYSTEM / "README.md"] = "\n".join(idx) + "\n"
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Compile per-repo ai-docs into norikit/ecosystem/.")
    ap.add_argument("--check", action="store_true", help="report drift; write nothing; exit 1 if drift")
    args = ap.parse_args()

    targets = build()
    drift = False
    for path, content in sorted(targets.items()):
        if path.exists() and path.read_text() == content:
            continue
        drift = True
        print(f"  ~ {path.relative_to(REPO)}")
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    print("  ✓ ecosystem/ in sync" if not drift else
          ("  (--check) drift detected" if args.check else "  regenerated ecosystem/"))
    if args.check and drift:
        sys.exit(1)


if __name__ == "__main__":
    main()
